### PR TITLE
Add sum-of-products for G1Projective and G2Projective

### PR DESCRIPTION
**Pull request by andrewwhitehead**
This code originates in [bls12_381_plus](https://github.com/mikelodder7/bls12_381_plus/) and is copied with permission. Written by @mikelodder7

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
For our use case this can be drastically faster when computing `p[0] * s[0] + ... + p[n] + s[n]` where `p` are G1 points and `s` are scalars. For example:

- n = 10: 4.9057 ms  vs  259.34 us  (94% faster)
- n = 100: 50.524 ms  vs  281.01 us  (99% faster)

**Comment by tarcieri** [comment]
Sidebar: it might be nice to have traits for this in e.g. the `group` crate.

We had a similar need in the `k256` crate: https://github.com/RustCrypto/elliptic-curves/pull/380

Maybe someone can open a tracking issue /cc @fjarri

**Comment by mikelodder7** [comment]
I’d be up for that.

**Comment by str4d** [comment]
We also have multiexponentiation arithmetic in the `halo2` crate, and it definitely seems like a good candidate for making generic in the `group` crate (in the same way I recently added generic batch-inversion logic to the `ff` crate).

In the meantime, I'll look at this PR in the next week or two.

**Comment by str4d** [comment]
I skimmed over the PR and it looks fine. However, @ebfull and I don't think that we should have an implementation of this here specifically; instead it should go generically into `group`. I've opened https://github.com/zkcrypto/group/issues/25 for tracking progress on this.

**Pull request closed without merging**
